services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DB}'
      - 'MYSQL_PASSWORD=${MYSQL_PASS}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}'
      - 'MYSQL_USER=${MYSQL_USER}'
    ports:
      - '3309:3306'
  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}'
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}'
    ports:
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
      - '15672:15672'


